FROM python:3

RUN mkdir -p /usr/share/fonts/truetype
COPY fonts/* /usr/share/fonts/truetype/

RUN fc-cache -fv

RUN mkdir /code
WORKDIR /code

ADD requirements.txt /code/
ADD requirements.dev.txt /code/
RUN pip install -r requirements.dev.txt

CMD ./manage.py wait_for_db && ./manage.py migrate && ./manage.py createcachetable && ./manage.py runserver 0.0.0.0:3000
