services:
  backend:
    container_name: pdf-gen-backend
    networks:
      - default
      - shared
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - db
    volumes:
      - ./:/code
    ports:
      - '3000:3000'
  db:
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres:15
    ports:
      - 5432:5432
version: '3.4'

networks:
  shared:
    name: mlp_network
